name: Build TWRP Recovery for M33x

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build and Release
    runs-on: ubuntu-latest

    env:
      DEVICE_NAME: m33x
      DEVICE_PATH: device/samsung/m33x
      DEVICE_TREE_URL: https://github.com/Android-Artisan/android_device_samsung_m33x.git
      DEVICE_TREE_BRANCH: main
      MANIFEST_URL: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
      MANIFEST_BRANCH: twrp-12.1

    steps:
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig \
            repo python-is-python3

      - name: Initialize TWRP repo
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init -u $MANIFEST_URL -b $MANIFEST_BRANCH
          repo sync -j$(nproc) --force-sync

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone --depth=1 --branch $DEVICE_TREE_BRANCH $DEVICE_TREE_URL $DEVICE_PATH

      - name: Prepare environment and lunch target
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch omni_${DEVICE_NAME}-eng

      - name: Build recovery image
        run: |
          cd ~/twrp
          mka recoveryimage -j$(nproc)

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          tag: twrp-${{ github.run_number }}
          name: TWRP for ${{ env.DEVICE_NAME }} - Build ${{ github.run_number }}
          body: |
            Automated TWRP build for `${{ env.DEVICE_NAME }}`
            Triggered by commit `${{ github.sha }}`
          files: |
            ~/twrp/out/target/product/${{ env.DEVICE_NAME }}/recovery.img
